steps:
  # Run the Maven build
  - name: gcr.io/mygcpcloudbuild/mymavengcpcloudbuild
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/$_PROJECT_ID/mygcpcloudbuildplanet', '.']
# images
#images: ['gcr.io/$_PROJECT_ID/mygcpcloudbuildplanet']
options:
  logging: CLOUD_LOGGING_ONLY

