steps:
  # Run the Maven build
  - name: gcr.io/mygcpcloudbuild/mymavengcpcloudbuild
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/effortless-gate-371410/mygcpcloudbuildplanet', '.']
# images
images: ['gcr.io/effortless-gate-371410/mygcpcloudbuildplanet']
options:
  logging: CLOUD_LOGGING_ONLY

